name: Scraping Barrages Maroc (Quotidien)

on:
  schedule:
    - cron: '15 9 * * *'
  workflow_dispatch:

jobs:
  scrape-and-store:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # تثبيت المكتبات مباشرة لضمان عدم توقف المحرك
          pip install pandas requests beautifulsoup4 lxml supabase python-dotenv

      - name: Run scraping script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python scraper_barrages_maroc.py
